### ISSUE TITLE
Support mfma_f32_16x16x16f16

### ISSUE THREAD

**Issue by hclearner** [ROCmSoftwarePlatform/flash-attention#21]
Hi, Does this project support mfma_f32_16x16x16f16, now it seems that only mfma_f32_32x32x8f16 supported. Thanks :)

**Comment by howiejayz** [comment]
Hi @hclearner, I believe the feature you are requesting are belong to the [Composable Kernel](https://github.com/ROCmSoftwarePlatform/composable_kernel/tree/mha-train-develop) backend.

**Comment by hengyeliu** [comment]
> Hi @hclearner, I believe the feature you are requesting belongs to the [Composable Kernel](https://github.com/ROCmSoftwarePlatform/composable_kernel/tree/mha-train-develop) backend.
Hello,I changed flash_attn_rocm's composable_kernel backend to mfma_f32_16x16x16f16, but get wrong result. Is there anything else need to be modified besides the GEMM parameter in  composable_kernel?

**Comment by howiejayz** [comment]
Please refer to this issue for the setting https://github.com/ROCmSoftwarePlatform/composable_kernel/issues/1074

**Comment by hclearner** [comment]
Has been solved, thanks:)
