### ISSUE TITLE
Is this v2 or v1?

### ISSUE THREAD

**Issue by netw0rkf10w** [ROCmSoftwarePlatform/flash-attention#26]
Hello,
Thanks for your great work! 
I would like to know if the current implementation is FA v1 or v2. If it’s v1 then are you planning to upgrade to v2?
Thank you in advance for your replies.

**Comment by howiejayz** [comment]
Hi @netw0rkf10w, this repo is synchronized to v2.0.4 of the upstream one.

**Comment by netw0rkf10w** [comment]
Thanks @howiejayz for your reply.
Could you tell me how the current repo compares to the [triton implementation](https://github.com/ROCmSoftwarePlatform/triton/blob/9517d4c2566cd2763d038b95b79713a04a36eac6/python/tutorials/06-fused-attention.py) in your other fork in terms of performance?
I'm trying to use flash attention on MI250x cards (and also MI300A ones), and am not sure which implementation I should use.
Thank you in advance!

**Comment by howiejayz** [comment]
Hi @netw0rkf10w, I think you should try the triton one if possbile. This version of Flash-Attention for ROCm is relatively old and the performance is not updated to the triton implementation.

**Comment by netw0rkf10w** [comment]
@howiejayz I see. Thanks a lot!
